### ISSUE TITLE
Enable Override support using clusterSelector

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/federation-v2#643] opened 2019-03-12 10:08 UTC
Now the `placement` already support `clusterSelector` which can enable the end user can select multiple clusters with a label.

But the `overrides` do not support `clusterSelector` now https://github.com/kubernetes-sigs/federation-v2/blob/master/example/sample1/federateddeployment.yaml#L28-L32 , how about enable it support as well?

/cc @marun

**Comment by kuanf** [comment] 2019-03-12 13:05
@gyliu513 when introducing clusterSelector into overrides, one concerns is the potential conflicts among overrides. May need to consider some sort of ordering of prioritization to the overrides if not random pick...

**Comment by marun** [comment] 2019-03-12 14:09
This appears to be a duplicate of #581, please close.

**Closed** 2019-03-12 23:21 UTC
