### ISSUE TITLE
federateddeployment delete is stuck waiting for a missing cluster

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/federation-v2#591] opened 2019-02-12 16:13 UTC
**What happened**:
- Deployed a FederatedDeployment to clusters c1,c2,c3
- Removed cluster c1
- kubectl delete federateddeployment nginx
```
Warning  DeleteFailed  7s (x16 over 2m1s)  federateddeployment-controller  Failed to delete FederatedDeployment "default/nginx": waiting for clusters c1 to become ready to verify that obj default/nginx has been deleted
```
- `kubectl get cluster -n kube-multicluster-public` lists c2,c3
-  `kubectl delete federateddeployment nginx --force --grace-period 0` does not work, command is stuck.

**Environment**:
- Kubernetes version (use `kubectl version`)
client: v1.12.1
server: v1.11.6-gke.2

- Federation version
latest

- Install method (helm vs script)
script
- Install configuration (namespaced vs cluster-scoped)
cluster-scoped

/kind bug

**Comment by matti** [comment] 2019-02-12 16:22
okay, so cluster is still present in `federatedclusters`, but I still think that `--force --grace-period 0` should work?

**Comment by matti** [comment] 2019-02-12 16:32
after:
```
kubectl delete federatedclusters.core.federation.k8s.io c1 -n federation-system
```
the federateddeployment disappeard.

opened #592

**Comment by marun** [comment] 2019-02-13 00:27
This is not a bug, it is a feature (though it does likely indicate a gap in the documentation).  The sync controller adds a finalizer to all federated resources the first time it reconciles them, and that finalizer is only removed once it is confirmed that the target resource does not exist on all registered clusters (and confirmation is only possible for reachable clusters).  This is to ensure that deletion of a federated resource guarantees deletion of target resources in the member clusters.

The only way to ensure removal of a federated resource after deletion has been initiated is to have the finalizer removed.  That can be accomplished by ensuring all registered clusters are reachable so that sync controller can confirm removal of target resources and remove the finalizer, or by manually removing the finalizer from the federated resource.

**Comment by matti** [comment] 2019-02-13 07:06
Agree, but shouldn't force delete work?

**Comment by marun** [comment] 2019-02-13 17:21
@matti As per the documentation on finalizers, kubernetes only removes an object if its list of finalizers is empty:

https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers

To clear finalizers manually:

```bash
kubectl patch <resource type> <resource name> -p '{"metadata":{"finalizers":null}}'
```

I encourage extreme caution in removing finalizers manually.   Kubernetes controllers use finalizers to ensure resource cleanup on deletion.

**Comment by marun** [comment] 2019-02-14 18:03
While I don't think there is a technical fix for this, I do think the role of finalizers in propagation needs to be clearly documented to avoid the confusion this issue represents.

**Comment by marun** [comment] 2019-04-10 01:38
The userguide has been updated documenting the role of finalizers in deletion of federated resources: https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#deletion-policy

**Closed by marun** 2019-04-10 01:38 UTC
Labels: kind/bug, kind/documentation
