### ISSUE TITLE
Namespaced install attempts to create cluster-wide CRDs

### ISSUE THREAD

**Issue by michaelfig** [kubernetes-sigs/federation-v2#731] opened 2019-04-08 23:32 UTC
**What happened**: I created a namespaced cluster with: 
```
NAMESPACED=true FEDERATION_NAMESPACE=dev scripts/deploy-federation-latest.sh my-cluster
```

then the deployed federation-controller in the "dev" namespace logs the following and exits:

```
Federation v2 controller-manager version: version.Info{Version:"v0.0.7", GitCommit:"3e251608ca5357080b95a0bedc45759652f17d29", GitTreeState:"clean", BuildDate:"2019-03-22T22:30:26Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
W0408 23:16:26.511755       1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0408 23:16:26.743345       1 log.go:172] Creating CRD clusterpropagatedversions.core.federation.k8s.io
F0408 23:16:26.747413       1 controller-manager.go:108] Could not create CRDs: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:dev:default" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

**What you expected to happen**: Namespaced federation would not reference any CRDs for cluster-scoped resources like "clusterpropagatedversions".

**How to reproduce it (as minimally and precisely as possible)**: Install with the above command on a cluster that's missing any federation-v2 cluster-level CRDs.

**Anything else we need to know?**:  The namespaced CRDs were created successfully by the namespaced Helm chart.  It's only the cluster-scope CRDs that are missing (and I would expect them to be missing, and not referenced in the federation-controller).

Federation controller arguments from the pod:
```yaml
  containers:
  - args:
    - --limited-scope=true
    - --federation-namespace=$(FEDERATION_NAMESPACE)
    - --registry-namespace=$(CLUSTER_REGISTRY_NAMESPACE)
    command:
    - /root/controller-manager
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: FEDERATION_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: CLUSTER_REGISTRY_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: quay.io/kubernetes-multicluster/federation-v2:latest
    imagePullPolicy: Always
```

**Environment**:
- Kubernetes version (use `kubectl version`) v1.13.2
- Federation version v2, v0.0.7
- Install method (helm vs script) script/deploy-federation-latest.sh
- Install configuration (namespaced vs cluster-scoped) namespaced
- Others

/kind bug

**Comment by marun** [comment] 2019-04-10 01:21
As of last week, the controller manager no longer has the ability to install CRDs, so it would not be possible to reproduce this bug with master.  However, until #701 is implemented there is no released chart and the documentation is not clear on the need to specify an image version when deploying from the chart in master.  Once #701 is released I think this issue can likely be closed.

**Comment by michaelfig** [comment] 2019-05-03 20:36
With the helm chart 0.0.9, I need the following doc fix:

```
--- a/docs/userguide.md
+++ b/docs/userguide.md
@@ -516,7 +516,7 @@ experimenting with federation on a production cluster.
 ### Helm Configuration
 
 To deploy a federation in a namespaced configuration, set
-`global.limitedScope` to `true` as per the Helm chart [install
+`global.scope` to `Namespaced` as per the Helm chart [install
 instructions](https://github.com/kubernetes-sigs/federation-v2/blob/master/charts/federation-v2/README.md#configuration).
```

but when I run the Helm install with `global.scope=Namespaced`, I get:

```
no matches for kind "FederatedTypeConfig" in version "core.federation.k8s.io/v1alpha1", unable to recognize "":
```

It seems that some cluster-wide CRDs are still required to do a namespaced install.

**Comment by marun** [comment] 2019-05-03 22:17
@michaelfig A fedv2 deployment depends on a number of API resources (e.g. `FederatedCluster`, `FederatedTypeConfig`, etc) that are deployed as CRDs.  CRDs are cluster-scoped resources even if the resources they represent are not (e.g. `FederatedCluster` is namespaced).  Therefore, deployment of federation depends on having sufficient permissions to create CRDs.

Assuming your use case requires allowing a non-privileged user to deploy namespaced federation, you could achieve this result by creating a chart that would create the CRDs common to deployments of federation.  This chart would need to be installed by a cluster admin. Another chart would deploy the resources required to run a namespaced control plane.  Since enabling propagation for a type requires creating a CRD representing the federated type, a cluster admin would have to perform that operation.

I'm going to close this issue since the original problem has been fixed. The control plane is no longer capable of creating crds as part of its execution, and a documented procedure for deploying a released version of the chart is now available.  Feel free to file a separate issue to continue discussion of non-privileged deployment of namespaced federation.

**Closed by marun** 2019-05-03 22:17 UTC
Labels: kind/bug
