### ISSUE TITLE
`unjoin` should succeed if some resources remove failed.

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/federation-v2#188] opened 2018-07-26 16:01 UTC
This is a follow up issue based on comments at https://github.com/kubernetes-sigs/federation-v2/pull/137#issuecomment-406447550

From @marun :  I am still stuck on error handling. Removal of any resource would ideally not fail if not found, ensuring that cleanup of partial configuration is possible.

/assign

**Comment by gyliu513** [comment] 2018-11-12 05:33
@xunpan can you help on this?

**Comment by raffaelespazzoli** [comment] 2018-11-12 13:47
from the #410 that was marked as a duplicate of this, I think that join should succeed if some of the resources that it would have created already exist. Join should update these resources to the desired state when possible. In order to do this join should use an `apply` strategy rather than a `create` strategy.

**Closed** 2018-11-22 00:49 UTC
