### ISSUE TITLE
unjoin - re-join flow doesn't work

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes-sigs/federation-v2#410] opened 2018-11-09 21:27 UTC
the flow of unjoining and rejoining clusters doesn't work because the unjoin does not clean the resources crested during join and the join fails if these resources are already present.

The unjoin - rejoin flow is needed to create idempotent installation scripts.

I don't know the implementation details behind the join phase, but if the created resources were created with the apply semantic, probably this would be enough to fix this issue.

**Comment by gyliu513** [comment] 2018-11-10 13:31
@raffaelespazzoli can you please append some output of the error message when you unjoin and then re-join?

@xunpan can you help on this?

**Comment by raffaelespazzoli** [comment] 2018-11-10 19:17
@gyliu513 I'd see something like this: 
```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/home/rspazzol/git/openshift-federation/ansible/roles/install-federation/files/bin/kubefed2", "join", "raffa1", "--cluster-context", "raffa1", "--host-cluster-context", "raffa1", "--add-to-registry", "--v=2"], "delta": "0:00:00.554151", "end": "2018-11-10 13:09:59.352751", "msg": "non-zero return code", "rc": 255, "start": "2018-11-10 13:09:58.798600", "stderr": "I1110 13:09:58.807372   19567 join.go:141] Args and flags: name raffa1, host: raffa1, host-system-namespace: federation-system, registry-namespace: kube-multicluster-public, kubeconfig: , cluster-context: raffa1, secret-name: , limited-scope: false, dry-run: false\nI1110 13:09:58.815129   19567 join.go:195] Performing preflight checks.\nI1110 13:09:59.132907   19567 join.go:283] Registering cluster: raffa1 with the cluster registry.\nI1110 13:09:59.179767   19567 join.go:292] Registered cluster: raffa1 with the cluster registry.\nI1110 13:09:59.179824   19567 join.go:216] Creating federation-system namespace in joining cluster\nI1110 13:09:59.222453   19567 join.go:224] Created federation-system namespace in joining cluster\nI1110 13:09:59.222506   19567 join.go:227] Creating cluster credentials secret\nI1110 13:09:59.222527   19567 join.go:418] Creating service account in joining cluster: raffa1\nI1110 13:09:59.268708   19567 join.go:428] Created service account: raffa1-raffa1 in joining cluster: raffa1\nI1110 13:09:59.268772   19567 join.go:444] Creating cluster role and binding for service account: raffa1-raffa1 in joining cluster: raffa1\nI1110 13:09:59.343927   19567 join.go:538] Could not create cluster role for service account: raffa1-raffa1 in joining cluster: raffa1 due to: clusterroles.rbac.authorization.k8s.io \"federation-controller-manager:raffa1-raffa1\" already exists\nI1110 13:09:59.344176   19567 join.go:448] Error creating cluster role and binding for service account: raffa1-raffa1 in joining cluster: raffa1 due to: clusterroles.rbac.authorization.k8s.io \"federation-controller-manager:raffa1-raffa1\" already exists\nI1110 13:09:59.344298   19567 join.go:233] Could not create cluster credentials secret: clusterroles.rbac.authorization.k8s.io \"federation-controller-manager:raffa1-raffa1\" already exists\nF1110 13:09:59.344410   19567 join.go:117] error: clusterroles.rbac.authorization.k8s.io \"federation-controller-manager:raffa1-raffa1\" already exists", "stderr_lines": ["I1110 13:09:58.807372   19567 join.go:141] Args and flags: name raffa1, host: raffa1, host-system-namespace: federation-system, registry-namespace: kube-multicluster-public, kubeconfig: , cluster-context: raffa1, secret-name: , limited-scope: false, dry-run: false", "I1110 13:09:58.815129   19567 join.go:195] Performing preflight checks.", "I1110 13:09:59.132907   19567 join.go:283] Registering cluster: raffa1 with the cluster registry.", "I1110 13:09:59.179767   19567 join.go:292] Registered cluster: raffa1 with the cluster registry.", "I1110 13:09:59.179824   19567 join.go:216] Creating federation-system namespace in joining cluster", "I1110 13:09:59.222453   19567 join.go:224] Created federation-system namespace in joining cluster", "I1110 13:09:59.222506   19567 join.go:227] Creating cluster credentials secret", "I1110 13:09:59.222527   19567 join.go:418] Creating service account in joining cluster: raffa1", "I1110 13:09:59.268708   19567 join.go:428] Created service account: raffa1-raffa1 in joining cluster: raffa1", "I1110 13:09:59.268772   19567 join.go:444] Creating cluster role and binding for service account: raffa1-raffa1 in joining cluster: raffa1", "I1110 13:09:59.343927   19567 join.go:538] Could not create cluster role for service account: raffa1-raffa1 in joining cluster: raffa1 due to: clusterroles.rbac.authorization.k8s.io \"federation-controller-manager:raffa1-raffa1\" already exists", "I1110 13:09:59.344176   19567 join.go:448] Error creating cluster role and binding for service account: raffa1-raffa1 in joining cluster: raffa1 due to: clusterroles.rbac.authorization.k8s.io \"federation-controller-manager:raffa1-raffa1\" already exists", "I1110 13:09:59.344298   19567 join.go:233] Could not create cluster credentials secret: clusterroles.rbac.authorization.k8s.io \"federation-controller-manager:raffa1-raffa1\" already exists", "F1110 13:09:59.344410   19567 join.go:117] error: clusterroles.rbac.authorization.k8s.io \"federation-controller-manager:raffa1-raffa1\" already exists"], "stdout": "", "stdout_lines": []}
```
sorry for the formatting, this is ansible's output.
In general I noticed that the secrets in the federation-system namespace and the clusterroles were the objects for which I was getting errors.

**Comment by gyliu513** [comment] 2018-11-11 02:06
@raffaelespazzoli I did some test to un-join and re-join, `kubefed2` works fine, can you please run `kubefed2` join and unjoin manually to see if it works and then check what is wrong with your ansible script?

### Unjoin cluster2, succeed.
```
root@gyliu-dev1:~/go/src/github.com/kubernetes-sigs/federation-v2# ./bin/kubefed2 unjoin cluster2 --cluster-context cluster2 --host-cluster-context cluster1 --remove-from-registry --v=2
I1110 18:02:27.013294   28407 unjoin.go:112] Args and flags: name cluster2, host-cluster-context: cluster1, host-system-namespace: federation-system, kubeconfig: , cluster-context: cluster2, dry-run: false
I1110 18:02:27.024585   28407 unjoin.go:166] Performing preflight checks for unjoin cluster: cluster2.
I1110 18:02:27.051670   28407 unjoin.go:253] Removing cluster: cluster2 from the cluster registry.
I1110 18:02:27.097270   28407 unjoin.go:261] Removed cluster: cluster2 from the cluster registry.
I1110 18:02:27.097314   28407 unjoin.go:179] Deleting federated cluster resource from namespace: federation-system for unjoin cluster: cluster2
I1110 18:02:27.161053   28407 unjoin.go:190] Deleted federated cluster resource from namespace: federation-system for unjoin cluster: cluster2
I1110 18:02:27.161135   28407 unjoin.go:317] Deleting cluster role binding for service account: cluster2-cluster1 in unjoining cluster: cluster2
I1110 18:02:27.208453   28407 unjoin.go:327] Deleted cluster role binding for service account: cluster2-cluster1 in unjoining cluster: cluster2
I1110 18:02:27.208485   28407 unjoin.go:330] Deleting service account cluster2-cluster1 in unjoining cluster: cluster2
I1110 18:02:27.214038   28407 unjoin.go:337] Deleted service account cluster2-cluster1 in unjoining cluster: cluster2
I1110 18:02:27.214067   28407 unjoin.go:204] Deleting federation namespace: federation-system from unjoin cluster: cluster2
I1110 18:02:27.219185   28407 unjoin.go:214] Deleted federation namespace: federation-system from unjoin cluster: cluster2
```

### Join cluster2 again, succeed.
```
root@gyliu-dev1:~/go/src/github.com/kubernetes-sigs/federation-v2# ./bin/kubefed2 join cluster2 --cluster-context cluster2 --host-cluster-context cluster1 --add-to-registry --v=2
I1110 18:02:51.772639   28424 join.go:141] Args and flags: name cluster2, host: cluster1, host-system-namespace: federation-system, registry-namespace: kube-multicluster-public, kubeconfig: , cluster-context: cluster2, secret-name: , limited-scope: false, dry-run: false
I1110 18:02:51.782340   28424 join.go:195] Performing preflight checks.
I1110 18:02:51.805633   28424 join.go:283] Registering cluster: cluster2 with the cluster registry.
I1110 18:02:51.877007   28424 join.go:292] Registered cluster: cluster2 with the cluster registry.
I1110 18:02:51.877056   28424 join.go:216] Creating federation-system namespace in joining cluster
I1110 18:02:51.884674   28424 join.go:224] Created federation-system namespace in joining cluster
I1110 18:02:51.884723   28424 join.go:227] Creating cluster credentials secret
I1110 18:02:51.884778   28424 join.go:418] Creating service account in joining cluster: cluster2
I1110 18:02:52.018171   28424 join.go:428] Created service account: cluster2-cluster1 in joining cluster: cluster2
I1110 18:02:52.018237   28424 join.go:444] Creating cluster role and binding for service account: cluster2-cluster1 in joining cluster: cluster2
I1110 18:02:52.044267   28424 join.go:453] Created cluster role and binding for service account: cluster2-cluster1 in joining cluster: cluster2
I1110 18:02:52.044318   28424 join.go:457] Creating common cluster role and binding for service account: cluster2-cluster1 in joining cluster: cluster2
I1110 18:02:52.063560   28424 join.go:466] Created common cluster role and binding for service account: cluster2-cluster1 in joining cluster: cluster2
I1110 18:02:52.063600   28424 join.go:469] Creating secret in host cluster: cluster1
I1110 18:02:52.073357   28424 join.go:696] Using secret named: cluster2-cluster1-token-7t928
I1110 18:02:52.091829   28424 join.go:728] Created secret in host cluster named: cluster2-mkxcv
I1110 18:02:52.091861   28424 join.go:478] Created secret in host cluster: cluster1
I1110 18:02:52.092145   28424 join.go:237] Cluster credentials secret created
I1110 18:02:52.092218   28424 join.go:239] Creating federated cluster resource
I1110 18:02:52.100348   28424 join.go:248] Created federated cluster resource
```

### Check cluster2 status, it is ready again.
```
root@gyliu-dev1:~/go/src/github.com/kubernetes-sigs/federation-v2# kubectl -n federation-system describe federatedclusters
Name:         cluster1
Namespace:    federation-system
Labels:       <none>
Annotations:  <none>
API Version:  core.federation.k8s.io/v1alpha1
Kind:         FederatedCluster
Metadata:
  Creation Timestamp:  2018-11-11T01:18:48Z
  Generation:          1
  Resource Version:    313085
  Self Link:           /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster1
  UID:                 bddfa1bd-e54f-11e8-9049-00163e01fa8a
Spec:
  Cluster Ref:
    Name:  cluster1
  Secret Ref:
    Name:  cluster1-pl5rk
Status:
  Conditions:
    Last Probe Time:       2018-11-11T02:02:48Z
    Last Transition Time:  2018-11-11T01:19:12Z
    Message:               /healthz responded with ok
    Reason:                ClusterReady
    Status:                True
    Type:                  Ready
Events:                    <none>


Name:         cluster2
Namespace:    federation-system
Labels:       <none>
Annotations:  <none>
API Version:  core.federation.k8s.io/v1alpha1
Kind:         FederatedCluster
Metadata:
  Creation Timestamp:  2018-11-11T02:02:52Z
  Generation:          1
  Resource Version:    313086
  Self Link:           /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster2
  UID:                 e58c423b-e555-11e8-9049-00163e01fa8a
Spec:
  Cluster Ref:
    Name:  cluster2
  Secret Ref:
    Name:  cluster2-mkxcv
Status:
  Conditions:
    Last Probe Time:       2018-11-11T02:02:48Z
    Last Transition Time:  2018-11-11T02:02:48Z
    Message:               /healthz responded with ok
    Reason:                ClusterReady
    Status:                True
    Type:                  Ready
Events:                    <none>
```

**Comment by gyliu513** [comment] 2018-11-11 02:09
@raffaelespazzoli For your issue, I think the unjoin failed, and this left some garbage data and caused re-join failed. I'd suggest you clean up your cluster and re-run this again. Please make sure unjoin succeed before you re-join again.

**Comment by gyliu513** [comment] 2018-11-12 02:40
Thanks @raffaelespazzoli , so here you want to enable `force join` here, let's get some comments from @marun for this, the only concern from me is that the `force join` may leave some garbage data.

@marun WDYT?

**Comment by marun** [comment] 2018-11-12 05:00
I think this issue is a duplicate of #188, and I'm closing accordingly.  `unjoin` should remove everything it can rather than bailing on the first error it encounters.  Feel free to reopen if you do not agree with my assessment.

**Closed by marun** 2018-11-12 05:00 UTC
